name: publish

on:
  push:
    branches:
      - 'develop'
      - 'main'

jobs:
  Make_VSIX:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16.13.x'
    - uses: haya14busa/action-cond@v1
      id: condval
      with:
        cond: ${{ github.ref == 'refs/heads/main' }}
        if_true: "minor"
        if_false: "patch"
    - name: Auto Increment Semver Action
      uses: MCKanpolat/auto-semver-action@1.0.5
      id: versioning
      with:
        releaseType: ${{ steps.condval.outputs.value }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Get version parameters
      shell: bash
      run: |
        echo "##[set-output name=build_timestamp;]$(echo $(date +%s))"
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: version_parameters
    - run: npm install -g vsce
    - run: npm install
    - name: Setup webview depedencies
      run: npm run setup-browser
    - name: Make vsix
      run: vsce package
    - name: publish
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "./*.vsix"
        commit: ${{ steps.version_parameters.outputs.branch }}
        tag: ${{ steps.versioning.outputs.version }}
        prerelease: ${{ github.ref != 'refs/heads/main' }}
